config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to:'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to:'portfolios#angular'
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {published: 1, draft: 0}
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body, :topic_id
  
  def should_generate_new_friendly_id?
   title_changed?
  end
  
  def self.published_by_order
    order("updated_at DESC")
  end
  
  belongs_to :topic, optional: true  
  has_many :comments, dependent: :destroy

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :sidebar, except: [:update, :destroy, :toggle_status, :create]
  
  access all: [:show, :index], user: {except: [:destroy, :new, :update, :create, :edit, :toggle_status
  ]}, site_admin: :all
  layout 'blog'
  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.page(params[:page]).per(5).published_by_order
    else
      @blogs = Blog.published.page(params[:page]).per(5).published_by_order
    end
    @page_title = "My blogs page"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new  
      @page_title = @blog.title
    else
      redirect_to blogs_path, notice: "You are not authorised to access this page"
    end  
  end
  
  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def toggle_status
      if @blog.draft?
        @blog.published!
      else
        @blog.draft!
      end
    redirect_to blogs_url, notice: 'Blog status was successfully changed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end
    
    def sidebar
    @side_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
  
  def status_text blog
    if blog.draft?
      "Publish this post?"
    else
      "Bring back to draft mode"  
    end  
  end  
  def status_class blog
    if blog.draft?
      "btn btn-success"
    else
      "btn btn-warning" 
    end  
  end  
end

app/views/blogs/_adminfunctions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="breadcrumb blogcrumb">
    <%= link_to status_text(blog), toggle_status_blog_path(blog), class: status_class(blog) %> 
    <span class="social-links"><%= link_to fa_icon('pencil'), edit_blog_path(blog)%> </span>
    <span class="social-links"><%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' }%> </span>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
    <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
    <p class="blog-post-meta"> Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> </p>
    <%= render partial: 'blogs/adminfunctions', locals: {blog: blog} %>
    <p><%= markdown blog.body %></p>
</div> <hr>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
 <% if blog.errors.any? %>
  <% blog.errors.full_messages.each do |error| %>
   <%= alert_generator error %>
  <% end %>
 <% end %>
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                selected: blog.topic_id,
                                include_blank: true
                              },
                              class: 'form-control'
                            )
    %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "Content" %>
  </div>
  
  <div class="form-group">
    <%= f.radio_button :status, 'draft', class:'btn btn-primary' %>
    <%= f.label :status, "Stay in Draft?" %>
    <%= f.radio_button :status, 'published', class:'btn btn-primary' %>
    <%= f.label :status, "Publish this?" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
    <h2>Editing Blog</h2>
    <%= render 'form', blog: @blog %>
    <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
<%= paginate @blogs %>
<%= render @blogs %>
<%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
<h2>New Blog</h2>
<%= render 'form', blog: @blog %>
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <h2><%= @blog.title %></h2>
  <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: "breadcrumb-item" %> 
    <span class="breadcrumb-item active"><%= @blog.title %> </span> 
    
    <span class="ml-auto"> <%= link_to fa_icon('pencil'), edit_blog_path(@blog) if logged_in?(:site_admin) %> </span>
    <span margin-left = "2px"> <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: "Are you sure you want to delete this post?"} if logged_in?(:site_admin) %> </span>
  </nav>
  <p><i> In <u><%= @blog.status %></u> mode </i></p>
  <p> <%= markdown @blog.body %> </p>
  <%= render 'comments/comment_form' %>
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
</div>