config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to:'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to:'portfolios#angular'
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  validates_presence_of :title,:body
  accepts_nested_attributes_for :technologies,  allow_destroy: true,
                                      reject_if: lambda { |attrs| attrs['name'].blank?}

  
  mount_uploader :main_image, PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader
  
  def self.by_position
    order("position ASC")
  end
  def self.angular
    where(subtitle: "Angular")
  end
  
  scope :ruby_on_rails_items, -> {where(subtitle: "Ruby on Rails")}
  
end  

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  before_action :set_param, only: [:show, :update, :edit, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :update, :create, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end
  
  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def new
      @portfolio_item = Portfolio.new
  end
  
  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def edit
    @portfolio_item = @param_id
    3.times { @portfolio_item.technologies.build}

  end
  def update
   @portfolio_item = @param_id
   
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def show
   @portfolio_item = @param_id
  end
  def destroy
  @portfolio_item = @param_id
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully destroyed.' }
    end
  end
  def set_param
    @param_id = Portfolio.find(params[:id])
  end
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end
  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def set_image(height: , width:)
   "https://via.placeholder.com/#{height}x#{width}"
  end
  
  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img.to_s
    elsif type == 'thumb'
      set_image(height: '350', width: '200')
    elsif type == 'main'
      set_image(height: '600', width: '400')
    end 
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
<% if portfolio_item.errors.any? %>
  <% portfolio_item.errors.full_messages.each do |error| %>
   <%= alert_generator error %>
  <% end %>
<% end %>
<div class='row'>
  <div class='col-md-6'>
    <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', autofocus: true %>
    </div>
    <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, class: 'form-control' %>
    </div>
    <div class="form-group " >
      <label class= "btn btn-info btn-block">
        Upload a main image<%= form.file_field :main_image, style: 'display:none;' %>
      </label>
    </div>
    <div class="form-group">
      <label class= "btn btn-info btn-block">
        Upload a thumb image<%= form.file_field :thumb_image, style: 'display:none;' %>
      </label>
    </div>
  </div>
  <div class='col-md-6'>
    <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 13 %>
    </div>
  </div>
</div>
<div class='md-col-12'>
  <h2>Technologies Used</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
      <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>
    <% plus = fa_icon "plus-square" %>
    <div class = "icon-big">
      <%= link_to_add_association plus, form, :technologies %>
    </div>
    <div class="form-group">
      <%= form.submit "Submit Portfolio Item", class:"btn btn-primary btn-block" %>
    </div>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: "100%" %>
    <p class="card-text"><span> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item)%> </span> <%= portfolio_item.subtitle %></p>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <% minus = fa_icon "minus-square" %>
    <%= f.label :name =%>
     <div class="icon-big">
      <%= f.text_field :name, class: 'form-control'=%> <%= link_to_remove_association minus, f %>
    </div>
  </div>

app/views/portfolios/angular.html.erb
<h1>Angular Items</h1>
<%= link_to "Create a new item", new_portfolio_path  if logged_in?(:site_admin) %>
<% @angular_portfolio_items.each do |portfolio_item| %>
  <h2>This the title - <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2> 
  <h3><%= portfolio_item.subtitle %></h3> 
  <p><%= portfolio_item.body %></p> 
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit this item",  edit_portfolio_path(portfolio_item) %>
  <%= link_to 'Delete this item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %><hr>

<% end %>

app/views/portfolios/edit.html.erb
<div class='container'>
  <h1>Edit this Portfolio Item</h1>
  <%= render "portfolios/form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper("sidebar-module alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>  
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class='container'>
  <h1>Create a new Portfolio Item</h1>
  <%= render "portfolios/form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'thumb'), width: '100%' %> <br>
    </div>  

    <div class = "col-md-5">
      <h1><%= @portfolio_item.title %> </h1>
      <em> <%= @portfolio_item.subtitle %> </em>
      <hr>
      <p> <%= @portfolio_item.body %></p>
      <hr>
      <h3> Technologies used</h3>
      <% @portfolio_item.technologies.each do |t| %>
      <p> <%= t.name =%> </p>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit this item", edit_portfolio_path, class: "btn btn-warning" %>
        </div>
      <% end %>
    </div> 
  </div>
</div>