config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to:'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to:'portfolios#angular'
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  resources :blogs do
    member do 
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">           
   <div class="inner">
     <h3 class="masthead-brand">Vedant Lohbare</h3>
        <nav class="nav nav-masthead home-space">
          <%= nav_helper 'nav-link','span' %>
          <%= login_helper 'nav-link' %>
        </nav>
    </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> <%= copyright_generator %>  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title"><%= link_to "Vedant's Blogs", blogs_path %></h1>
    <p class="lead blog-description">Well check my blog.</p>
    <%= link_to 'Write a new one', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light blog-nav sticky-top shadow-sm p-3 mb-5 bg-white rounded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Vedant Lohbare", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Hey I am vedant. Want to hang out with me?</p>
  </div>
  
  
  <%= source_helper("sidebar-module alert alert-info sidebar-source") %>

 
  <div class="sidebar-module sidebar-module-inset">
    <h4>Topics</h4>
      <% @side_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic) %></p>
      <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Connect with me on these</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://www.github.com" target="_blank"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.facebook.com" target="_blank"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://www.twitter.com" target="_blank"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.instagram.com" target="_blank"><%= fa_icon "instagram" %></a></li>
      <ol>
  </div>
</div>

app/views/shared/_nav.html.erb
  <div class= "<%= location %>">
      <div><%= link_to 'Home', root_path %></div>
      <div><%=  link_to 'About', about_me_path %></div>
      <div><%=  link_to 'Contact', contact_path %></div>
      <div><%=  link_to 'Blogs', blogs_path %></div>
      <div><%=  link_to 'Portfolios', portfolios_path %></div>    
    </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View all portfolios", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to "Read more about me", about_me_path, class: "btn btn-primary" %>
      <%= link_to "Read more of what I write", blogs_path, class: "btn btn-secondary"%>
    </p>
  </div>
  <%= link_to 'Write a new Portfolio', new_portfolio_path  if logged_in?(:site_admin) %>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark sticky-top" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">The name is Vedant Lohbare.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white','li' %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark fixed-top">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Vedant Lohbare</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>